# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
  bind:
    host: 127.0.0.1
    port: ${PORT}
  url: ${BASE_URL}
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    # First language is the default language
    - ja-JP
    - en-US
  cors: true
  pretty_print: false
  limit: 20
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
  level: ${PYGEOAPI_LOG_LEVEL}

metadata:
  identification:
    title:
      ja: 八王子市ハザードマップ
      en: Hachioji Hazard Map
    description:
      ja: 東京都八王子市ハザードマップ API (Tokyo OSS Party!! 2021 チームI)
      en: Hazard Map API of Hachioji, Tokyo (Tokyo OSS Party!! 2021 Team I)
    keywords:
      ja:
        - ハザードマップ
        - api
      en:
        - hazardmap
        - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://www.city.hachioji.tokyo.jp/emergency/bousai/m12873/001/p005647.html
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: 東京都八王子市
    url: https://www.city.hachioji.tokyo.jp/contents/open/001/p005861.html
  contact:
    name: Miyoshi, Takahiro
    # position: Position Title
    address: 元本郷町三丁目24番1号
    city: 八王子市
    stateorprovince: 東京都
    postalcode: 〒192-8501
    country: Japan
    # phone: +xx-xxx-xxx-xxxx
    # fax: +xx-xxx-xxx-xxxx
    email: takahiro-miyoshi@sankichi.net
    # url: Contact URL
    # hours: Mo-Fr 08:00-17:00
    # instructions: During hours of service. Off on weekends.
    # role: pointOfContact

resources:
  obs:
    type: collection
    title: 避難所
    description: 東京都八王子市避難場所・避難所
    keywords:
      - shelter
    # context:
    #   - datetime: https://schema.org/DateTime
    #   - vocab: https://example.com/vocab#
    #     stn_id: "vocab:stn_id"
    #     value: "vocab:value"
    links:
      - type: text/html
        rel: alternate
        title: Yahoo!天気・災害
        href: https://crisis.yahoo.co.jp/map/result/?z=13&jis=13201
        hreflang: ja-JP
    extents:
      spatial:
        bbox: [139.21, 35.60, 139.43, 35.71]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: CSV
        data: data/hachioji_hinanjo.csv
        id_field: ID
        title_field: 名称
        geometry:
          x_field: 経度
          y_field: 緯度
